# Copyright 2018 Barroux Abbey (https://www.barroux.org/)
# @author: Alexis de Lattre <alexis.delattre@akretion.com>
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

{
    'name': 'Fruit Mill',
    'version': '12.0.1.0.0',
    'category': 'Manufacturing',
    'license': 'AGPL-3',
    'summary': 'Manage an fruit mill',
    'author': 'Akretion,Barroux Abbey',
    'website': 'https://github.com/akretion/vertical-fruit-mill',
    'depends': [
        'mrp',
        'account',
        'product_expiry_simple',
        'base_location',
        # 'stock_no_negative',  # ??
        #'stock_pack_operation_auto_fill',
        'report_py3o',
        'base_usability',  # for reports
        'onchange_helper',
        'base_view_inheritance_extension',
        ],
    'data': [
        'security/fruit_security.xml',
        'security/ir.model.access.csv',
        'data/decimal_precision.xml',
        'data/sequence.xml',
        'data/organic_certifying_entity.xml',
        #'data/cron.xml',
        'report/report.xml',
        'views/menu.xml',
        'wizard/fruit_palox_case_lend_view.xml',
        'wizard/fruit_palox_generate_production_view.xml',
        'wizard/fruit_withdrawal_view.xml',
        'wizard/fruit_invoice_create_view.xml',
        'wizard/fruit_juice_production_ratio2force_view.xml',
        'wizard/fruit_juice_production_force_ratio_view.xml',
        'wizard/fruit_juice_production_pack2check_view.xml',
        'wizard/fruit_juice_tank_transfer.xml',
        'wizard/fruit_arrival_warning_view.xml',
        'wizard/fruit_juice_production_compensation_view.xml',
        'wizard/fruit_juice_production_product_swap_view.xml',
        'wizard/fruit_juice_tank_merge_view.xml',
        'wizard/fruit_juice_bottling_view.xml',
        'wizard/fruit_juice_picking_view.xml',
        'wizard/fruit_appointment_print_view.xml',
        'wizard/fruit_juice_production_day_print_view.xml',
        'wizard/fruit_partner_warning_print_view.xml',
        'views/fruit_config_settings.xml',
        'views/stock_location.xml',
        'views/stock_warehouse.xml',
        'views/stock_picking.xml',
        'views/fruit_variant.xml',
        'views/fruit_ochard.xml',
        'views/fruit_parcel.xml',
        'views/fruit_palox.xml',
        'views/fruit_season.xml',
        'views/fruit_lended_case.xml',
        'views/fruit_cultivation.xml',
        'views/fruit_treatment.xml',
        'views/fruit_arrival.xml',
        #'views/fruit_juice_production.xml',
        'views/partner_organic_certification.xml',
        'views/fruit_appointment.xml',
        'views/fruit_preseason_poll.xml',
        'views/fruit_sale_pricelist.xml',
        'views/organic_certifying_entity.xml',
        #'views/partner.xml',
        'views/users.xml',
        'views/product.xml',
        'views/stock_production_lot.xml',
        'views/fruit_juice_analysis.xml',
    ],
    'demo': [
        'demo/product.xml',
        'demo/fruit_variant.xml',
        'demo/company.xml',
        'demo/fruit_sale_pricelist.xml',
        'demo/partner.xml',
        'demo/stock_production_lot.xml',
        'demo/stock_location.xml',
        'demo/stock_warehouse.xml',
        'demo/fruit_ochard.xml',
        'demo/fruit_season.xml',
        'demo/fruit_treatment.xml',
        'demo/fruit_parcel.xml',
        'demo/fruit_palox.xml',
        ],
    'installable': True,
    'application': True,
}
