
from . import partner
from . import users
from . import product
from . import company
from . import fruit_config_settings
from . import stock_warehouse
from . import fruit_variant
from . import fruit_treatment
from . import fruit_season
from . import fruit_ochard
from . import fruit_palox
from . import fruit_parcel
from . import fruit_lended_case
from . import organic_certifying_entity
from . import partner_organic_certification
from . import fruit_cultivation
from . import fruit_appointment
from . import fruit_preseason_poll
from . import fruit_arrival
from . import fruit_juice_production
from . import fruit_juice_analysis
from . import fruit_sale_pricelist
from . import stock_location
from . import stock_production_lot
from . import stock_picking
from . import mrp_bom
from . import account_invoice
